### ISSUE TITLE
onTimeout() not working

### ISSUE THREAD

**Issue by ghost** [quentin7b/android-location-tracker#11]
I'm using the code below in a Service. Everything works, except for the onTimeOut();
### How to reproduce:
1. Turn on Location on device
2. Load an app with the code below
3. Once it starts the tracking, don't move the phone
4. Wait for the 10 seconds and see how there's no logged message

```
        TrackerSettings settings =
                new TrackerSettings()
                        .setUseGPS(true)
                        .setUseNetwork(true)
                        .setUsePassive(true)
                        .setTimeBetweenUpdates(10 * 1000); // 10 sec

        LocationTracker tracker = new LocationTracker(getApplicationContext(), settings) {
            @Override
            public void onTimeout() {
                Log.d("LocationTracker", "onTimeout");
            }
            @Override
            public void onLocationFound(Location location) {
                Log.d("LocationTracker", "onLocationFound");
            }
        };
        tracker.startListening();
```

**Comment by qk7b** [comment]
I'me not sure I get the issue.

If you don't provide a _timeout_ with `setTimeout()` in `TrackerSettings` then the default _timeout_ is `60 sec` (See on [TrackerSettings](https://github.com/quentin7b/android-location-tracker/blob/master/simple-location-tracker/slt/src/main/java/fr/quentinklein/slt/TrackerSettings.java#L139))

And then the _timeout_ is only triggered if there is _no position_ found so event if you do not move the phone but there is a _location_ found it will not trigger `onTimeout()` but `onLocationFound()`

**Comment by ghost** [comment]
Oh, I misunderstood `onTimeout()`. Sorry. :disappointed:

**Comment by qk7b** [comment]
No problem on that :smile: , may be I should explain it more clearly in the _readme_

**Comment by ghost** [comment]
However, on the code block below, [this line](https://github.com/quentin7b/android-location-tracker/blob/master/simple-location-tracker/slt/src/main/java/fr/quentinklein/slt/LocationTracker.java#L133) (**!mIsLocationFound && mIsListening**) is scoping `onTimeout()`:

``` java
if (mTrackerSettings.getTimeout() != -1) {
    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
            if (!mIsLocationFound && mIsListening) {
                Log.i(TAG, "No location found in the meantime");
                LocationTracker.this.stopListening();
                onTimeout();
            }
        }
    }, mTrackerSettings.getTimeout());
}
```

And taking into account that **mIsLocationFound** is [defined](https://github.com/quentin7b/android-location-tracker/blob/2e9a2c1209d9f4b7313a8c474df35b26341e1352/simple-location-tracker/slt/src/main/java/fr/quentinklein/slt/LocationTracker.java#L43):

``` java
private boolean mIsLocationFound = false;
```

Changed to `true` only  when a location has changed:

``` java
@Override
public final void onLocationChanged(@NonNull Location location) {
    Log.i(TAG, "Location has changed, new location is " + location);
    LocationTracker.sLocation = new Location(location);
    mIsLocationFound = true;
    onLocationFound(location);
}
```

Therefore, if a location was previously found, `onTimeout()` would not occur.

**Comment by qk7b** [comment]
Yes, this was the goal of the `onTimeout` callback when I wrote it.
If there is no location found after a delay, then this is a _timeout_.

What would you expect for this method ?

**Comment by ghost** [comment]
In my imagination, I was expecting this:
`setTimeBetweenUpdates(x)`: That worked like a thread with a runnable that request a **location update** each `x` milliseconds. If a location was found, it calls `onLocationFound()`, otherwise it runs again.

`setOnTimeout(y)`: A callback when there's no **location change** during `y`.

But `onTimeout` as a **delay** is cool. Thank you, and again, sorry for the misunderstandings, I'm still a novice with this things.
