### ISSUE TITLE
leak issue found

### ISSUE THREAD

**Issue by jjhesk** [quentin7b/android-location-tracker#16]
There was an anonymous subclass of fr.quentinklein.slt.LocationTracker and the anonymous implementation of java.lang.Runnnable.
This issue was tracked by leakcanary

**Comment by leonardo2204** [comment]
Got the same issue, trying to figure out

**Comment by leonardo2204** [comment]
To fix it, simply use the applicationContext() instead of the Activity context.

**Comment by qk7b** [comment]
In the next release, I wont store the context anymore. 
It will be given when needed, used, and this is it.

I knew it was a bad call to store it (without any kind of WeakRef or something) but anyway, it must be removed.
