### ISSUE TITLE
Possible setTimeBetweenUpdates() issue

### ISSUE THREAD

**Issue by iaindownie** [quentin7b/android-location-tracker#26]
Hi - just wanted to raise an issue I've recently encountered (possibly anecdotal and not tested thoroughly), but couldn't find any documentation defining or discussing it.

I had .setTimeBetweenUpdates(500) set, and some devices were reporting very slow location updates, up to about 9-10 seconds when it should have been every 1/2 second.

I slowed location polling down to .setTimeBetweenUpdates(1000) and it started updating at the correct times on all affected devices.

I wondered if there was a minimum value that should be mentioned in the docs, or a bug in the method? Either way it's fixed my issues, might help others.

**Comment by qk7b** [comment]
Hi !

Thanks for reporting.
I've not tested an update on 500ms myself either.

Behind the scene, the library uses the [Location Manager](https://developer.android.com/reference/android/location/LocationManager).

As specified in the doc

> Choosing a sensible value for minTime is important to conserve battery life. Each location update requires power from GPS, WIFI, Cell and other radios. Select a minTime value as high as possible while still providing a reasonable user experience. If your application is not in the foreground and showing location to the user then your application should avoid using an active provider (such as NETWORK_PROVIDER or GPS_PROVIDER), but if you insist then select a minTime of 5 * 60 * 1000 (5 minutes) or greater. If your application is in the foreground and showing location to the user then it is appropriate to select a faster update interval.

It seems there is no minimum...

But looking at the documentation, the method name (`setTimeBetweenUpdates`) is not well chosen (my bad) as it configures the `minTime` parameter on the `requestLocationUpdates` method. 

And as specified

> The location update interval can be controlled using the minTime parameter. The elapsed time between location updates **will never be less** than minTime, although it can be more depending on the Location Provider implementation and the update interval requested by other applications.

Doesn't mean it *will BE* the interval but it *couldn't be less*.

So from a pure semantic point of view on Android doc ... Getting an update every 10 seconds with a minTime at 500ms is OK.
Maybe I should change the name of the method and its doc.

**Comment by iaindownie** [comment]
Thanks Quentin. Yeah, renaming it to something like `setMinTimeBetweenUpdates` would be more accurate. Thanks again for your time and API development!

**Comment by qk7b** [comment]
Should be good in [4.0](https://github.com/quentin7b/android-location-tracker/releases/tag/4.0) :)
