### ISSUE TITLE
check if  LocationTracker is still listening for updates

### ISSUE THREAD

**Issue by Lir10** [quentin7b/android-location-tracker#3]
Hi , 

First of all , great lib! 

I wanted to ask if ther is any method i can check that  LocationTracker is still listening for location updates ?

**Comment by qk7b** [comment]
Hi !

Thanks :) Unfortunately, the method you want doesn't exist right now. But the information field is present in `LocationTracker.java`

```
/**
 * Indicates if Tracker is listening for updates or not
 */
private boolean isListening = false;
```

I'll add it in the next release.
