### ISSUE TITLE
Enhanced LocationTracker.Listener

### ISSUE THREAD

**Issue by andob** [quentin7b/android-location-tracker#32]
In the latest version (you rewrote the library in Kotlin, version 4.0), please add ``onProviderDisabled``, ``onProviderEnabled``, ``onStatusChanged`` methods to the ``LocationTracker.Listener`` interface.

With the previous version, written in Java, I used to extend the ``LocationTracker`` class. This class was implementing ``android.location.LocationListener`` so I used to override ``onProviderDisabled``, ``onProviderEnabled`` in the extended class. Now I cannot do this anymore.

**Comment by andob** [comment]
I reimplemented the feature on my app using a different approach.

But I think this would make a nice useful addition to the library. :)

**Comment by qk7b** [comment]
Looks like a great idea.

**Comment by qk7b** [comment]
I've opened a PR on the subject. 
The goal is to add the opportunity to monitor it without forcing the user to do it.
So I've added a new listener type to do it

**Comment by andob** [comment]
ok, great!
