### ISSUE TITLE
check any of given provider is enabled ?

### ISSUE THREAD

**Issue by DJafari** [quentin7b/android-location-tracker#4]
how can check LocationManager can detect location from any given providers ?

**Comment by qk7b** [comment]
AFAIK, there are 3 different providers in the Android [LocationManager](http://developer.android.com/reference/android/location/LocationManager.html) (the class android-location-tracker is using):
- GPS_PROVIDER
- NETWORK_PROVIDER
- PASSIVE_PROVIDER

The `TrackerSettings` class helps you enable/disable and check those 3 providers.
- `setUseGPS()`
- `setUseNetwork()`
- `setUsePassive()`
  and
- `shouldUseGPS()`
- `shouldUseNetwork()`
- `shouldUsePassive()`

So if your tracker settings return `true` for the 3 above methods, then it _can detect location from any given providers_.
Is that answering your question ?

**Comment by DJafari** [comment]
no, i enabled GPS for example in TracketSettings, but user disabled gps of device, how can check device gps is enabled ? or totally, LocationTracker can detect user location or not ?

**Comment by qk7b** [comment]
Ok, I get it.
To check if the provider is enabled physically, Android provides the `isProviderEnabled()` method.
In the `LocationTracker` I check if this is the case before using it. But the library doesn't provide any way to check this. You have to do it by yourself at the moment.

See [Stackoverflow](http://stackoverflow.com/questions/843675/how-do-i-find-out-if-the-gps-of-an-android-device-is-enabled).

Maybe it's a good idea to add some methods to help doing it, I'll check that.

**Comment by DJafari** [comment]
i know that, it's good in your library add method to found that in simple api

thanks

**Comment by qk7b** [comment]
I'll do it in the next version.

**Comment by qk7b** [comment]
Done in https://github.com/quentin7b/android-location-tracker/releases/tag/v3.0

**Comment by DJafari** [comment]
thanks
