### ISSUE TITLE
Callback for "not enabled" errors

### ISSUE THREAD

**Issue by ghost** [quentin7b/android-location-tracker#9]
Provide a callback for this problems:
- GPS_PROVIDER is not enabled
- NETWORK_PROVIDER is not enabled
- PASSIVE_PROVIDER is not enabled

**Comment by qk7b** [comment]
I'm looking for the best way to do that.
For now I have 2 options:
- 3 methods more in the `LocationTracker`, `onGpsProviderError()`, `onNetworkProviderError()` and `onPassiveProviderError()` **might be overriden** but **not abstract**, one for each provider error
- A single method like `onProviderError(ProviderError)` with a specific throwable for each provider or something.

As a user, could you tell me what would be the best ?

Thanks,

**Comment by ghost** [comment]
I guess the most common thing to do when there's a _not enabled_ error is to render a message for the user, letting him know that you're having problems trying to retrieve his location.

So, I would prefer to use single method  `onProviderError(ProviderError)` to handle the 3 errors.

**Comment by qk7b** [comment]
See #13, if it's ok, then I'll close
